### ISSUE TITLE
캘린더 관련 오류 현상

### ISSUE THREAD

**Issue by nyangzzi** [nyangzzi/WithConimal#2]
# Issue

- 캘린더 날짜가 8자리 미만인 경우, 미선택으로 표기되는 오류 발생
- 캘린더 Title Top 색상 관련 이슈
- 연월 선택 feature 없음

# Goal

- 캘린더 날짜가 8자리 미만인 경우, 미선택으로 표기되는 이슈 해결
- 캘린더 Title Top이 색상 변경되어야 함
- 연월 선택 feature 추가 필요

# Task

- [ ] 캘린더 날짜 관련 오류 해결
  - [ ] 1번 해결책
  - [ ] 2번 해결책
- [ ] 캘린더 Title Top 색상 변경
  - [ ] 1번 해결책
- [ ] 연월 선택 feature 추가
  - [ ] feature 추가
